apiVersion: v1
kind: ConfigMap
metadata:
    name: {{include "devops-app.fullname" .}}-config
data:
    AAP_NAME: {{.Values.config.APP_NAME | quote }}
    LOG_LEVEL: {{.Values.config.LOG_LEVEL | quote }}
